[versions]
hilt = "2.57.2"
app-compat = "1.7.1"
junit = "4.13.2"
gson = "2.13.2"
lotti = "6.6.10"
hilt-navigation = "1.3.0"
compose-activity = "1.11.0"
compose-bom = "2025.10.01"
compose-navigation = "2.9.5"
retrofit = "3.0.0"
okhttp = "5.2.1"
mockk = "1.14.6"
sys-ui = "0.36.0"
paparazzi = "1.3.5"
android-gradle-plugin = "8.11.2"
kotlin = "2.2.21"
hilt-plugin = "2.57.2"
ksp = "2.3.0"
moshi = "1.15.2"
material3 = "1.0.0-alpha12"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt-plugin" }
google-services = { id = "com.google.gms.google-services", version = "4.3.15" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
snapit = { id = "uk.adbsalam.snapit", version = "1.0.8" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
app-compat = { group = "androidx.appcompat", name = "appcompat", version.ref = "app-compat" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material = { group = "androidx.compose.material3", name = "material3", version = "1.4.0-alpha14" }
compose-views-material = { group = "com.google.android.material", name = "material", version = "1.13.0" }
compose-nav = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version="1.7.8" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-lotti = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lotti" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-system-ui = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "sys-ui" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation" }
ktx-core = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }

okhttp = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
moshi = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
gradle-api = { group = "com.android.tools.build", name = "gradle-api", version.ref = "android-gradle-plugin" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
youtube-player = { group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "core", version = "12.1.0" }
youtube-player-seekbar = { group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "custom-ui", version = "12.1.0" }
play-services-nearby = { group = "com.google.android.gms", name = "play-services-nearby", version = "18.5.0" }
material3 = { group = "androidx.xr.compose.material3", name = "material3", version.ref = "material3" }
